# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35tfgg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/Courses/CPU/Pipeline/Pipeline.cache/wt [current_project]
set_property parent.project_path E:/Courses/CPU/Pipeline/Pipeline.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo e:/Courses/CPU/Pipeline/Pipeline.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  E:/Courses/CPU/Pipeline/src/designs/cpu/ALU.v
  E:/Courses/CPU/Pipeline/src/designs/cpu/ALUControl.v
  E:/Courses/CPU/Pipeline/src/designs/cpu/BranchTest.v
  E:/Courses/CPU/Pipeline/src/designs/cpu/Bus.v
  E:/Courses/CPU/Pipeline/src/designs/cpu/CPU.v
  E:/Courses/CPU/Pipeline/src/designs/cpu/Control.v
  E:/Courses/CPU/Pipeline/src/designs/cpu/DataMemory.v
  E:/Courses/CPU/Pipeline/src/designs/cpu/pipeline_registers/EX_MEM_Reg.v
  E:/Courses/CPU/Pipeline/src/designs/cpu/ForwardControl.v
  E:/Courses/CPU/Pipeline/src/designs/cpu/HazardUnit.v
  E:/Courses/CPU/Pipeline/src/designs/cpu/pipeline_registers/ID_EX_Reg.v
  E:/Courses/CPU/Pipeline/src/designs/cpu/pipeline_registers/IF_ID_Reg.v
  E:/Courses/CPU/Pipeline/src/designs/cpu/InstructionMemory.v
  E:/Courses/CPU/Pipeline/src/designs/external_devices/LED.v
  E:/Courses/CPU/Pipeline/src/designs/cpu/pipeline_registers/MEM_WB_Reg.v
  E:/Courses/CPU/Pipeline/src/designs/cpu/PCOnBreak.v
  E:/Courses/CPU/Pipeline/src/designs/cpu/ProgramCounter.v
  E:/Courses/CPU/Pipeline/src/designs/cpu/RegisterFile.v
  E:/Courses/CPU/Pipeline/src/designs/external_devices/SSD.v
  E:/Courses/CPU/Pipeline/src/designs/external_devices/SysTick.v
  E:/Courses/CPU/Pipeline/src/designs/external_devices/Timer.v
  E:/Courses/CPU/Pipeline/src/designs/external_devices/UART.v
  E:/Courses/CPU/Pipeline/src/designs/external_devices/UART_Rx.v
  E:/Courses/CPU/Pipeline/src/designs/external_devices/UART_Tx.v
  E:/Courses/CPU/Pipeline/src/designs/cpu/clk_gen.v
  E:/Courses/CPU/Pipeline/src/designs/top.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/Courses/CPU/Pipeline/src/constraints/ego1.xdc
set_property used_in_implementation false [get_files E:/Courses/CPU/Pipeline/src/constraints/ego1.xdc]

read_xdc E:/Courses/CPU/Pipeline/src/constraints/top.xdc
set_property used_in_implementation false [get_files E:/Courses/CPU/Pipeline/src/constraints/top.xdc]


synth_design -top top -part xc7a35tfgg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
