# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "E:/Courses/CPU/Pipeline/.Xil/Vivado-21184-LAPTOP-IPU5LKLQ/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7a35tfgg484-1

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog {
      E:/Courses/CPU/Pipeline/src/designs/cpu/ALU.v
      E:/Courses/CPU/Pipeline/src/designs/cpu/ALUControl.v
      E:/Courses/CPU/Pipeline/src/designs/cpu/BranchTest.v
      E:/Courses/CPU/Pipeline/src/designs/cpu/Bus.v
      E:/Courses/CPU/Pipeline/src/designs/cpu/CPU.v
      E:/Courses/CPU/Pipeline/src/designs/cpu/Control.v
      E:/Courses/CPU/Pipeline/src/designs/cpu/DataMemory.v
      E:/Courses/CPU/Pipeline/src/designs/cpu/pipeline_registers/EX_MEM_Reg.v
      E:/Courses/CPU/Pipeline/src/designs/cpu/ForwardControl.v
      E:/Courses/CPU/Pipeline/src/designs/cpu/HazardUnit.v
      E:/Courses/CPU/Pipeline/src/designs/cpu/pipeline_registers/ID_EX_Reg.v
      E:/Courses/CPU/Pipeline/src/designs/cpu/pipeline_registers/IF_ID_Reg.v
      E:/Courses/CPU/Pipeline/src/designs/cpu/InstructionMemory.v
      E:/Courses/CPU/Pipeline/src/designs/external_devices/LED.v
      E:/Courses/CPU/Pipeline/src/designs/cpu/pipeline_registers/MEM_WB_Reg.v
      E:/Courses/CPU/Pipeline/src/designs/cpu/PCOnBreak.v
      E:/Courses/CPU/Pipeline/src/designs/cpu/ProgramCounter.v
      E:/Courses/CPU/Pipeline/src/designs/cpu/RegisterFile.v
      E:/Courses/CPU/Pipeline/src/designs/external_devices/SSD.v
      E:/Courses/CPU/Pipeline/src/designs/external_devices/SysTick.v
      E:/Courses/CPU/Pipeline/src/designs/external_devices/Timer.v
      E:/Courses/CPU/Pipeline/src/designs/external_devices/UART.v
      E:/Courses/CPU/Pipeline/src/designs/external_devices/UART_Rx.v
      E:/Courses/CPU/Pipeline/src/designs/external_devices/UART_Tx.v
      E:/Courses/CPU/Pipeline/src/designs/cpu/clk_gen.v
      E:/Courses/CPU/Pipeline/src/designs/top.v
    }
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top top
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter enableSplitFlowPath "E:/Courses/CPU/Pipeline/.Xil/Vivado-21184-LAPTOP-IPU5LKLQ/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] && [info exists rt::doParallel] && $rt::doParallel} { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] && [info exists rt::doParallel] && $rt::doParallel} { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
